name: GoldmannAndCable
channels:
  - conda-forge
dependencies:
  #- python=3.6
  #- pip=19.1*
  # - sphinx
  # - coverage
  #- cython=0.29*
  #- nose=1.3*
  - matplotlib
  #=3.1*
  - scipy
  - brian2
  #- ipympl
  #- pip:
  #  - brian2tools
